version: "3.9"

services:
  gpt_plugin:
    build: ./
    image: linnil1/hono_cf_proxy_qa_gpt4
    environment:
      - OPENAI_KEY=...
      - AUTH_TOKEN=openai_token
      - EMBEDDING_NAME=text-embedding-ada-002
      # - EMBEDDING_NAME=text-embedding-3-large
    ports:
      - 5001:5001
    volumes:
      - ./index_text-embedding-ada-002:/app/index_text-embedding-ada-002:ro
    #   - ./:/app/
