name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3.30.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            OAUTH_GITHUB_CLIENT_ID
            OAUTH_GITHUB_CLIENT_SECRET
            JWT_SECRET
        env:
          OAUTH_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          OAUTH_GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
